/*
 * File: app/view/MainPanel.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('kgm.view.MainPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.mainpanel',

    requires: [
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.Toolbar',
        'Ext.field.Select',
        'Ext.field.Search'
    ],

    config: {
        id: 'MainPanel',
        layout: 'card',
        items: [
            {
                xtype: 'list',
                itemTpl: [
                    '<div>{ime} {prezime} {familia}</div>',
                    '<div>{seria} {number}</div>'
                ],
                store: 'MyJsonPStore'
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'selectfield',
                        flex: 0,
                        docked: 'left',
                        id: 'txtSeria',
                        itemId: 'txtSeria',
                        width: '50%',
                        label: 'Серия:',
                        labelWidth: '50%',
                        options: [
                            {
                                text: 'А',
                                value: 'А'
                            },
                            {
                                text: 'Б',
                                value: 'Б'
                            }
                        ]
                    },
                    {
                        xtype: 'searchfield',
                        id: 'txtSearch',
                        width: '100%',
                        label: '№:'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onTxtSearchKeyup',
                event: 'keyup',
                delegate: '#txtSearch'
            }
        ]
    },

    onTxtSearchKeyup: function(textfield, e, eOpts) {
        //var seria = Ext.getCmp('txtSeria').getValue();
        //var search = Ext.getCmp('txtSearch').getValue();
        //var store = Ext.getStore('MyJsonPStore');
        //console.log(store);

        Ext.Viewport.setMasked({ xtype: 'loadmask', message: 'Зареждам ...', indicator:true});

                var seria = Ext.getCmp('txtSeria').getValue();
                var search = Ext.getCmp('txtSearch').getValue();


                if(search.length > 0 && search.length < 5)

                {
                    var store = Ext.getStore('MyJsonPStore');
                    store.autoLoad = false;
                    store.load(
                        {
                            params: {
                                seria: seria,
                                number: search
                            },
                            callback: function(records, operation, success) {

                                if(success)
                                {
                                    Ext.Viewport.setMasked(false);
                                   // Ext.Viewport.animateActiveItem(Ext.create('Contacts.view.MainTabPanel'),{type:'flip',duration: 400});
                                  //  Ext.Viewport.setMasked(false);
                                    console.log('success');
                                }
                                else
                                {
                                    Ext.Viewport.setMasked(false);
                                    Ext.Msg.alert('Събщение', 'Грешна парола или потребителско име.', Ext.emptyFn);
                                    console.log('unsuccess');
                                }
                            },
                            scope: this
                        });

                }
                else
                {
                    Ext.Msg.alert('Събщение', 'Полетата "Потребител" и "Парола" са задължителни за попълване', Ext.emptyFn);
                    Ext.Viewport.setMasked(false);
                }


    }

});