/*
 * File: app/view/UsersKgmDetailsView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('iagKgmMob.view.UsersKgmDetailsView', {
    extend: 'Ext.dataview.List',
    alias: 'widget.userskgmdetailsview',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        title: 'Резултат ...',
        centered: false,
        fullscreen: false,
        id: 'list',
        modal: false,
        emptyText: '<h3>Нама регистрирана такава марка</h3>',
        store: 'UsersKgmStore',
        itemTpl: [
            '<h1>{Ime} {Prezime} {Familia}</h1>',
            '<p>ул. {AddressP},</p>',
            '<p>гр.(с) {PolpulatedPlace}, общ. {Municipality},</p>',
            '<p>обл. {Region},</p>',
            '<p>тел. {PhoneMob}</p>',
            '	'
        ]
    }

});