/*
 * File: app/model/MyModel.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('kgm.model.MyModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'ime'
            },
            {
                name: 'prezime'
            },
            {
                name: 'familia'
            },
            {
                name: 'seria'
            },
            {
                name: 'number'
            }
        ],
        validations: [
            {
                type: 'length',
                field: 'number',
                max: 4,
                min: 1
            }
        ]
    }
});