/*
 * File: app/controller/KgmController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('iagKgmMob.controller.KgmController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            searchByKgmBtn: '#searchByKgmBtn',
            navigationviewbynokgm: 'navigationviewbynokgm'
        },

        control: {
            "searchByKgmBtn": {
                tap: 'onButtonTap'
            }
        }
    },

    onButtonTap: function(button, e, eOpts) {
        Ext.Viewport.setMasked({ xtype: 'loadmask', message: 'Зареждам КГМ ...', indicator:true});

        var SeriaKGM = Ext.getCmp('txtBySeria').getValue();
        var KGM = Ext.getCmp('txtByKgm').getValue();

            if(SeriaKGM.length > 0 && KGM.length > 0)
            {
                var store = Ext.getStore('KgmSearchStore');

                store.load({
                    params: {
                        SeriaKGM:SeriaKGM,
                        KGM:KGM
                    },
                    callback: function(records, operation, success) {

                        if(success)
                        {
                            Ext.Viewport.setMasked(false);

                            this.getNavigationviewbynokgm().push({
                                xtype:'kgmuserresultview',
                                title:'Резултат'
                            });
                        }
                        else
                        {
                            Ext.Viewport.setMasked(false);
                            Ext.Msg.alert('Събщение', 'Няма регистрирана такава марка.', Ext.emptyFn);
                        }
                    },
                    scope: this
                });
            }
            else
            {
                Ext.Msg.alert('Събщение', 'Полетата "Серия" и "№ на КГМ" са задължителни. Изберете Серията от падащия списък, въведете № на КГМ (Например: "6894" или "0056") и натиснете бутона "Намери"', Ext.emptyFn);
                Ext.Viewport.setMasked(false);

            }

    }

});