/*
 * File: app/view/HomeView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('iagKgmMob.view.HomeView', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.homeview',

    requires: [
        'iagKgmMob.view.NavigationViewHome',
        'iagKgmMob.view.NavigationViewByName',
        'iagKgmMob.view.NavigationViewByNoKgm',
        'iagKgmMob.view.NavigationViewAbout',
        'Ext.tab.Bar',
        'Ext.navigation.View'
    ],

    config: {
        fullscreen: true,
        layout: {
            type: 'card',
            animation: 'slide',
            'animation.duration': 1000
        },
        tabBar: {
            docked: 'bottom'
        },
        items: [
            {
                xtype: 'navigationviewhome',
                title: 'Начало',
                html: '',
                iconCls: 'home'
            },
            {
                xtype: 'navigationviewbyname',
                title: 'По Име',
                iconCls: 'search'
            },
            {
                xtype: 'navigationviewbynokgm',
                scrollable: 'vertical',
                title: 'По № КГМ',
                iconCls: 'search'
            },
            {
                xtype: 'navigationviewabout',
                scrollable: true,
                title: 'За нас',
                iconCls: 'info'
            }
        ]
    }

});