/*
 * File: app/view/NavigationViewByName.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('iagKgmMob.view.NavigationViewByName', {
    extend: 'Ext.navigation.View',
    alias: 'widget.navigationviewbyname',

    requires: [
        'Ext.Panel',
        'Ext.form.FieldSet',
        'Ext.field.Text',
        'Ext.Button'
    ],

    config: {
        disabled: false,
        scrollable: 'vertical',
        defaultBackButtonText: 'Обратно',
        items: [
            {
                xtype: 'panel',
                title: 'По име',
                items: [
                    {
                        xtype: 'fieldset',
                        centered: true,
                        margin: 30,
                        instructions: 'Въведете мин. първите 3 букви от името или първаите букви от името и фамилията с интервал между тях',
                        title: 'Търсене по име:',
                        items: [
                            {
                                xtype: 'textfield',
                                id: 'txtByName',
                                label: '',
                                required: true
                            },
                            {
                                xtype: 'button',
                                centered: false,
                                docked: 'bottom',
                                id: 'searchByNameBtn',
                                itemId: 'mybutton1',
                                margin: '50 50',
                                maxWidth: '',
                                ui: 'confirm-round',
                                iconAlign: 'center',
                                iconCls: 'search',
                                text: 'Намери'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});