/*
 * File: app/view/NavigationViewByNoKgm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('iagKgmMob.view.NavigationViewByNoKgm', {
    extend: 'Ext.navigation.View',
    alias: 'widget.navigationviewbynokgm',

    requires: [
        'Ext.Panel',
        'Ext.form.FieldSet',
        'Ext.field.Select',
        'Ext.Button'
    ],

    config: {
        items: [
            {
                xtype: 'panel',
                title: 'По № КГМ',
                items: [
                    {
                        xtype: 'fieldset',
                        centered: true,
                        maxWidth: 400,
                        instructions: 'Изберете серията от падащото меню и въведете № на Контролна горска марка. Натиснете бутона "Намери" за търсене. Номерът е във формат "0013".',
                        title: 'Търсене по серия и  № на КГМ',
                        items: [
                            {
                                xtype: 'selectfield',
                                border: 2,
                                centered: false,
                                id: 'txtBySeria',
                                margin: '5 5',
                                label: 'Серия:',
                                required: true,
                                readOnly: false,
                                options: [
                                    {
                                        text: 'А',
                                        value: 'А'
                                    },
                                    {
                                        text: 'Б',
                                        value: 'Б'
                                    },
                                    {
                                        text: 'В',
                                        value: 'В'
                                    },
                                    {
                                        text: 'Г',
                                        value: 'Г'
                                    },
                                    {
                                        text: 'Д',
                                        value: 'Д'
                                    },
                                    {
                                        text: 'Е',
                                        value: 'Е'
                                    }
                                ]
                            },
                            {
                                xtype: 'textfield',
                                border: 2,
                                id: 'txtByKgm',
                                margin: '60 5 5 5',
                                label: '№ КГМ:',
                                name: '',
                                required: true,
                                maxLength: 4
                            },
                            {
                                xtype: 'button',
                                docked: 'bottom',
                                id: 'searchByKgmBtn',
                                margin: '50 50',
                                ui: 'confirm-round',
                                iconCls: 'search',
                                text: 'Намери'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});