/*
 * File: app/model/KgmModel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('iagKgmMob.model.KgmModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'ID'
            },
            {
                name: 'UdoKgmID'
            },
            {
                name: 'UdoNoID'
            },
            {
                name: 'NumberZaiavlenie'
            },
            {
                name: 'DateZaiavlenie'
            },
            {
                name: 'SeriaKGM'
            },
            {
                name: 'field25'
            },
            {
                name: 'ModelKGM'
            },
            {
                name: 'Ime'
            },
            {
                name: 'Prezime'
            },
            {
                name: 'Familia'
            },
            {
                name: 'EGN_EIK'
            },
            {
                name: 'PolpulatedPlace'
            },
            {
                name: 'Municipality'
            },
            {
                name: 'Region'
            },
            {
                name: 'PhoneMob'
            },
            {
                name: 'AddressP'
            }
        ]
    }
});